# Tutorial: The Perceptron
> Created: Aug. 2024 for the FSU Course: *Machine Learning in Physics* <br>
> Updated: Aug 25 2026, Add another exercise.<br>
> H. B. Prosper<br>

The perceptron, defined by
\begin{align}
    y & = g(x\,A^\text{T} + b),
\end{align}
is the basic computational element of neural networks. 
<img src="./perceptron.png" align="left" width="400px"/> In the simplest case, the output $y$ and the bias $b$ are row matrices, while the input $x$ is a matrix consisting of one or more rows.
<br clear="left"/>

## Tips

  * Use __esc r__ to disable a cell
  * Use __esc y__ to reactivate it
  * Use __esc m__ to go to markdown mode. **Markdown** is the typesetting language used in jupyter notebooks.
  * In a markdown cell, double tap the mouse or glide pad (on your laptop) to go to edit mode. 
  * Shift + return to execute a cell (including markdown cells).
  * If the equations don't typeset, try double tapping the cell again, and re-execute it.

## Import modules 

In [1]:
import numpy as np
import torch

## Input Data
The input data can consist of one or more rows. We make the data type ($\texttt{dtype}$) $\texttt{float32}$ to be compatible with $\texttt{PyTorch}$.

In [3]:
x = np.array([-2.0, 1.0, 4.0], dtype=np.float32)
print(x)

[-2.  1.  4.]


## Perceptron Parameters

In [4]:
# Perceptron 1
A1 = np.array([2,-3, 1], dtype=np.float32)
b1 = -5

# Perceptron 2
A2 = np.array([1, 2, 3], dtype=np.float32)
b2 = -4

### Perceptron 1: $z_1 = x \, A_1^\text{T} + b_1$; $y_1 = g(z_1)$

In [6]:
z1 = x @ A1.T + b1
y1 = np.maximum(0, z1) # relu

print(f'''
    x A1^T + b1 => z1: {z1:5.1f}
    relu(z1)    => y1: {y1:5.1f} 
''')


    x A1^T + b1 => z1:  -8.0
    relu(z1)    => y1:   0.0 



### Perceptron 2: $z_2 = x \, A_2^\text{T} + b_2$; $y_2 = g(z_2)$

In [8]:
z2 = x @ A2.T + b2
y2 = np.maximum(0, z2)

print(f'''
    x A2^T + b2 => z2: {z2:5.1f}
    relu(z2)    => y2: {y2:5.1f} 
''')


    x A2^T + b2 => z2:   8.0
    relu(z2)    => y2:   8.0 



## Multi-node Perceptron

Construct a 2-node perceptron with 3 inputs.

In [12]:
A = np.vstack([A1, A2]) # vertical stack 

b = np.hstack([b1, b2]) # horizontal stack 

print('shape:', A.shape)
print(A)
print()

print('shape:', b.shape)
print(b)

shape: (2, 3)
[[ 2. -3.  1.]
 [ 1.  2.  3.]]

shape: (2,)
[-5 -4]


Compute output of perceptron

In [13]:
z = x @ A.T + b
y = np.maximum(0, z)
z, y

(array([-8.,  8.]), array([0., 8.]))

## Do the same using $\texttt{PyTorch}$

In [19]:
# Instantiate a linear function with 3 inputs and 2 outputs
linear = torch.nn.Linear(3, 2)

print(f'''
    A.shape: {linear.weight.shape}
    A:       {linear.weight}
''')

# Instantiate a relu function that will be applied
# elementwise to its matrix argument.
relu = torch.nn.ReLU()

# Compute output of a (3, 2) perceptron
with torch.no_grad(): # Disable gradient calculation     
    linear.weight.copy_(torch.tensor(A)) 
    linear.bias.copy_(torch.tensor(b))
    z = linear(torch.tensor(x)) # compute linear function
    y = relu(z)
    
print(z, y)


    A.shape: torch.Size([2, 3])
    A:       Parameter containing:
tensor([[ 0.2997, -0.5574,  0.0457],
        [ 0.2534,  0.1182, -0.1745]], requires_grad=True)

tensor([-8.,  8.]) tensor([0., 8.])


## Exercises 

 1. Build a model, $f(x, \omega)$, using `numpy`, with two layers and randomly assigned weights and biases. *Hint* 1:  use `help(np.random)` to get help on `numpy`'s random number generators. *Hint* 2: learn about the `reshape` function using `help(np.reshape)`.
    1. Layer 1: 3 inputs ($x$), 4 outputs, relu
    2. Layer 2: 4 inputs, 1 output, $y$
    3. Compute $y$ given $x$ 
 2. Build the same model using `PyTorch` with the same weights and biases.  Compare the outputs.
 3. Create an `numpy` array of shape $(10, 3)$, that is, 10 rows and 3 columns filled with random numbers. Compare the outputs of a `numpy` and `PyTorch` version of the code.

