# The Perceptron
> Created Aug. 2024 for the FSU Course: *Machine Learning in Physics* <br>
> H. B. Prosper<br>

The perceptron, defined by
\begin{align}
    y & = g(x\,A^\text{T} + b),
\end{align}
is the basic computational element of neural networks. 
<img src="./perceptron.png" align="left" width="400px"/> The output $y$ and and the bias $b$ are row matrices, while the input $x$ is a matrix consisting of one or more rows.
<br clear="left"/>

## Tips

  * Use __esc r__ to disable a cell
  * Use __esc y__ to reactivate it
  * Use __esc m__ to go to markdown mode. **Markdown** is the typesetting language used in jupyter notebooks.
  * In a markdown cell, double tap the mouse or glide pad (on your laptop) to go to edit mode. 
  * Shift + return to execute a cell (including markdown cells).
  * If the equations don't typeset, try double tapping the cell again, and re-execute it.

## Import modules 

In [1]:
import numpy as np
import torch

## Input Data
The input data can consist of one or more rows. We make the data type ($\texttt{dtype}$) $\texttt{float32}$ to be compatible with $\texttt{PyTorch}$.

In [2]:
x = np.array([-2.0, 1.0, 4.0], dtype=np.float32)

## Perceptron Parameters

In [3]:
# Perceptron 1
A1 = np.array([2,-3, 1], dtype=np.float32)
b1 = -5

# Perceptron 2
A2 = np.array([1, 2, 3], dtype=np.float32)
b2 = -4

### Perceptron 1: $z_1 = x \, A_1^\text{T} + b_1$; $y_1 = g(z_1)$

In [4]:
z1 = x @ A1.T + b1
y1 = np.maximum(0, z1)
z1, y1

(-8.0, 0.0)

### Perceptron 2: $z_2 = x \, A_2^\text{T} + b_2$; $y_2 = g(z_2)$

In [5]:
z2 = x @ A2.T + b2
y2 = np.maximum(0, z2)
z2, y2

(8.0, 8.0)

## Multi-node Perceptron

Construct a 2-node perceptron with 3 inputs.

In [6]:
A = np.vstack([A1, A2]) # vertical stack 

b = np.hstack([b1, b2]) # horizontal stack 

A.shape, A, b.shape, b

((2, 3),
 array([[ 2., -3.,  1.],
        [ 1.,  2.,  3.]], dtype=float32),
 (2,),
 array([-5, -4]))

Compute output of perceptron

In [7]:
z = x @ A.T + b
y = np.maximum(0, z)
z, y

(array([-8.,  8.]), array([0., 8.]))

## Do the same using $\texttt{PyTorch}$

In [8]:
# instantiate a linear function with 3 inputs and 2 outputs
linear = torch.nn.Linear(3, 2)

# instantiate a relu function that will be applied
# elementwise to its matrix argument.
relu = torch.nn.ReLU()

# compute output of a (3, 2) perceptron
with torch.no_grad(): # disable gradient calculation     
    linear.weight.copy_(torch.tensor(A)) 
    linear.bias.copy_(torch.tensor(b))
    z = linear(torch.tensor(x)) # compute linear function
    y = relu(z)
z, y

(tensor([-8.,  8.]), tensor([0., 8.]))